name: maas_sayaci
description: Maas Sayaci - maasin 30 gun boyunca nasil aktigini canli izleyen eglenceli uygulama.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"

  google_mobile_ads: ^5.1.0
